### ISSUE TITLE
How was this delivered?

### ISSUE THREAD

**Issue by strickinato** [osfameron/lambdalounge-mar-2022#1]
Hey @osfameron  -- I watched [the talk](https://youtu.be/03AY8rUObR8?t=2117) - I loved the style of delivery!

What program did you use to highlight each line as you went through the file?

**Comment by osfameron** [comment]
Hi Aaron, thanks, and glad you enjoyed it!

I'll add something to README later, good call. But briefly:

Limelight.vim does the highlighting, it's a great extension!

```
Plug 'junegunn/limelight.vim'
let g:limelight_conceal_ctermfg = 7
```

(color will depend on your terminal and vim colorschemes, I'm using solarized-light)

And I executed in Bash using Vim 8's terminal (for the first time, so I stole and adapted this code from StackOverflow I think -- will check source for README)

```
function s:exec_on_term(lnum1, lnum2)
  " get terminal buffer
  let g:terminal_buffer = get(g:, 'terminal_buffer', -1)
  " open new terminal if it doesn't exist
  if g:terminal_buffer == -1 || !bufexists(g:terminal_buffer)
    rightb vert terminal bash
    let g:terminal_buffer = bufnr('')
    wincmd p
  " split a new window if terminal buffer hidden
  elseif bufwinnr(g:terminal_buffer) == -1
    exec 'sbuffer ' . g:terminal_buffer
    wincmd p
  endif
  " join lines with "\<cr>", note the extra "\<cr>" for last line
  " send joined lines to terminal.
  call term_sendkeys(g:terminal_buffer,
        \ join(getline(a:lnum1, a:lnum2), "\<cr>") . "\<cr>")
endfunction

command! -range ExecOnTerm call s:exec_on_term(<line1>, <line2>)
noremap <leader>= m`}kv{j:ExecOnTerm<cr><esc>``
inoremap <leader>= <ESC>m`}kv{j:ExecOnTerm<esc><cr>``
```

**Comment by osfameron** [comment]
https://vi.stackexchange.com/a/19875

**Comment by strickinato** [comment]
Sweet! Thanks!! `limelight` ended up being the perfect search term to find a similar package that will work better for my lifestyle:

https://github.com/larstvei/Focus :trollface:

(as an aside, I also had fun with your Carp presentation 😄  - thanks for presenting!)
